-- db/script_oracle.sql
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 200
SET LINESIZE 200
SPOOL evidencia_conexion_bd/ddl_y_inserts_ok.txt

-- Drops seguros 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reservas CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE laboratorios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- Tablas
CREATE TABLE usuarios (
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   VARCHAR2(100) NOT NULL,
  email    VARCHAR2(120) NOT NULL UNIQUE
);

CREATE TABLE laboratorios (
  id_lab        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(100) NOT NULL,
  ubicacion     VARCHAR2(150),
  capacidad     NUMBER(4),
  encargado_id  NUMBER
);

CREATE TABLE reservas (
  id_reserva   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha        DATE NOT NULL,
  hora_inicio  VARCHAR2(5) NOT NULL,  -- HH24:MI
  hora_fin     VARCHAR2(5) NOT NULL,  -- HH24:MI
  id_lab       NUMBER NOT NULL,
  id_usuario   NUMBER NOT NULL
);

-- FK
ALTER TABLE reservas ADD CONSTRAINT fk_res_usu FOREIGN KEY (id_usuario) REFERENCES usuarios(id);
ALTER TABLE reservas ADD CONSTRAINT fk_res_lab FOREIGN KEY (id_lab) REFERENCES laboratorios(id_lab);

-- Índices sobre FKs
CREATE INDEX idx_res_usu ON reservas(id_usuario);
CREATE INDEX idx_res_lab ON reservas(id_lab);

-- Datos coherentes 
INSERT INTO usuarios (nombre, email) VALUES ('María Pérez', 'maria@institucion.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Juan Soto',  'juan@institucion.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Ana Díaz',   'ana@institucion.cl');

INSERT INTO laboratorios (nombre, ubicacion, capacidad, encargado_id) VALUES ('Lab Redes',        'Edificio B, Sala 203', 30, 1);
INSERT INTO laboratorios (nombre, ubicacion, capacidad, encargado_id) VALUES ('Lab Programación', 'Edificio A, Sala 101', 25, 2);
INSERT INTO laboratorios (nombre, ubicacion, capacidad, encargado_id) VALUES ('Lab Electrónica',  'Edificio C, Sala 305', 20, 3);

INSERT INTO reservas (fecha, hora_inicio, hora_fin, id_lab, id_usuario) VALUES (DATE '2025-11-03', '09:00', '11:00', 1, 2);
INSERT INTO reservas (fecha, hora_inicio, hora_fin, id_lab, id_usuario) VALUES (DATE '2025-11-04', '10:00', '12:00', 2, 1);
INSERT INTO reservas (fecha, hora_inicio, hora_fin, id_lab, id_usuario) VALUES (DATE '2025-11-05', '08:30', '10:30', 3, 3);

COMMIT;

-- Verificación rápida 
PROMPT ====== RECUENTO TABLAS ======
SELECT 'USUARIOS' tabla, COUNT(*) total FROM usuarios
UNION ALL SELECT 'LABORATORIOS', COUNT(*) FROM laboratorios
UNION ALL SELECT 'RESERVAS', COUNT(*) FROM reservas;

PROMPT ====== JOIN RESERVAS-DETALLE ======
SELECT r.id_reserva, TO_CHAR(r.fecha,'YYYY-MM-DD') AS fecha,
       r.hora_inicio, r.hora_fin,
       l.nombre AS lab, u.nombre AS usuario
FROM reservas r
JOIN laboratorios l ON l.id_lab = r.id_lab
JOIN usuarios u     ON u.id     = r.id_usuario
ORDER BY r.id_reserva;

SPOOL OFF
EXIT
